[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29.0"
rand = "0.9.2"
log = "0.4.28"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
